# Generated by Django 4.2 on 2023-04-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Post',
            new_name='post',
        ),
    ]
