# Generated by Django 4.2.1 on 2023-05-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
    ]
