# Generated by Django 4.2.1 on 2023-05-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_post_likes_alter_post_user_like_post_like_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_num',
        ),
        migrations.AddField(
            model_name='post',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
