# Generated by Django 4.2.1 on 2023-05-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_post_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='main_app_userprofile',
        ),
    ]
