# Generated by Django 4.2.1 on 2023-05-20 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0019_userprofile_followers_alter_userprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='reposts',
            field=models.ManyToManyField(related_name='reposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
