# Generated by Django 4.2.1 on 2023-05-22 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0020_post_repost_num_post_reposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reposts',
        ),
        migrations.AddField(
            model_name='post',
            name='repost',
            field=models.ManyToManyField(related_name='repost', to=settings.AUTH_USER_MODEL),
        ),
    ]
