# Generated by Django 4.2.1 on 2023-06-09 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0022_alter_post_content_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(related_name='liked_posts', through='main_app.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
