# Generated by Django 4.2.1 on 2023-06-10 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_remove_post_liked_alter_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_num',
        ),
    ]
